### ISSUE TITLE
Error while train bot with unicode data(persian)

### ISSUE THREAD

**Issue by onlydarkknight** [gunthercox/ChatterBot#407]
When i try to train my bot with persian (unicode) data that already stored in corpus/data/persian folder and get responce from bot, this error occure:
Here is my sample code,any help or suggestion please!
and sorry for my bad english:

```python
# -*- coding: utf-8 -*-
from chatterbot import ChatBot

chatbot = ChatBot(
    'Ron Obvious',
    trainer='chatterbot.trainers.ChatterBotCorpusTrainer'
)
chatbot.train("chatterbot.corpus.persian")
print chatbot.get_response(u"سلام")
```

and below is last lines of error

```
....
File "D:\Python27\Lib\site-packages\jsondb\file_writer.py", line 26, in write_data
    db.write(encode(obj))
  File "D:\Python27\lib\encodings\cp1256.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 2-7: character maps to <undefined>
```

**Comment by gunthercox** [comment]
Hi @onlydarkknight, I've made changes to correct the issue. I've also added a unit test to make sure this doesn't break again in the future. These changes will be available when I release the next version of ChatterBot.

Thank you for posting both your example code and the error traceback. It made debugging the issue much easier.

**Comment by onlydarkknight** [comment]
thank you for your reply.
But i'm working on a project (a telegram bot) and want use this package for chat section.Therefore i cant wait for next version.
Is it possible for you to post changes or help me to correct this issue myself.

**Comment by gunthercox** [comment]
You don't have to wait. I released the next version this morning. Version 0.4.13 includes the fix.

**Comment by onlydarkknight** [comment]
Hello again and thanks for your reply
I download latest version of package but still have same error,therefore i test same code with hindi corpus data but still same error occurred.below is new example code :
```
# -*- coding: utf-8 -*-
from chatterbot import ChatBot

chatbot = ChatBot(
'Ron Obvious',
trainer='chatterbot.trainers.ChatterBotCorpusTrainer'
)
# Train based on the hindi corpus
# chatbot.train("chatterbot.corpus.english")
chatbot.train("chatterbot.corpus.hindi.greetings")
print chatbot.get_response( u"नमस्ते")
# Train based on the english corpus
# chatbot.train("chatterbot.corpus.english")

```
and error:

 ```
File "D:\Python27\Lib\site-packages\chatterbot\storage\jsonfile.py", line 145, in update
    self.database.data(key=statement.text, value=data)
  File "D:\Python27\Lib\site-packages\jsondb\db.py", line 77, in data
    self._set_content(key, value)
  File "D:\Python27\Lib\site-packages\jsondb\db.py", line 41, in _set_content
    data = write_data(self.path, obj)
  File "D:\Python27\Lib\site-packages\jsondb\file_writer.py", line 26, in write_data
    db.write(encode(obj))
  File "D:\Python27\lib\encodings\cp1256.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 2-7: character maps to <undefined>

```
i attached image of pip list command to see my package version.
![capture](https://cloud.githubusercontent.com/assets/23508966/20861485/b11050f0-b9a6-11e6-80fe-3f89928eff8a.PNG)

**Comment by gunthercox** [comment]
Looking at the traceback, it appears that the issue is coming from the `jsondb` package (`File "D:\Python27\Lib\site-packages\jsondb\db.py"`). Please make sure you have the latest version installed by running `pip install jsondatabase --upgrade`

You may also find that you need to encode test from the response statement to display it in the terminal. I've added an example bellow to help you.

```python
# -*- coding: utf-8 -*-
from chatterbot import ChatBot

chatbot = ChatBot(
    'Ron Obvious',
    trainer='chatterbot.trainers.ChatterBotCorpusTrainer'
)
chatbot.train("chatterbot.corpus.hindi.greetings")

text = unicode(u"नमस्ते")
response = chatbot.get_response(text)
print response.text.encode('utf-8')
```

**Comment by onlydarkknight** [comment]
Thanks again
i test my jsondatabase version and it is up to date already.also test your example code and still get same error as bellow:
```
Traceback (most recent call last):
  File "D:/Python27/telebot-master/chater.py", line 8, in <module>
    chatbot.train("chatterbot.corpus.hindi.greetings")
  File "D:\Python27\Lib\site-packages\chatterbot\trainers.py", line 117, in train
    trainer.train(pair)
  File "D:\Python27\Lib\site-packages\chatterbot\trainers.py", line 90, in train
    self.storage.update(statement, force=True)
  File "D:\Python27\Lib\site-packages\chatterbot\storage\jsonfile.py", line 145, in update
    self.database.data(key=statement.text, value=data)
  File "D:\Python27\Lib\site-packages\jsondb\db.py", line 77, in data
    self._set_content(key, value)
  File "D:\Python27\Lib\site-packages\jsondb\db.py", line 41, in _set_content
    data = write_data(self.path, obj)
  File "D:\Python27\Lib\site-packages\jsondb\file_writer.py", line 26, in write_data
    db.write(encode(obj))
  File "D:\Python27\lib\encodings\cp1256.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 2-7: character maps to <undefined>
```
did you test your example code and run with no error?

**Comment by gunthercox** [comment]
I was able to run the example I posted without error. In the traceback you posted, the part that says `character maps to <undefined>` looks very odd to me. Is it possible that the default encoding isn't set on your computer? To check this, what is the output of:

```python
import sys
print sys.getdefaultencoding()
```

**Comment by onlydarkknight** [comment]
Also i test your example test code in python command line step by step(marked in yellow in attached image) and got same error again(surrounded with red color line), and it seems printing unicode to console doesn't cause error;while when i run command `chatbot.train("chatterbot.corpus.hindi.greetings")` this error occurred
![chater](https://cloud.githubusercontent.com/assets/23508966/20899449/b8990534-bb3f-11e6-9eaa-24c69cbf2ab9.PNG)
.

**Comment by mrmrn** [comment]
Dear @onlydarkknight ,
Did you solve the problem?
